### ISSUE TITLE
[1.12.2] Server Crash loading Game: NoClassDefFound Error

### ISSUE THREAD

**Issue by Morpheus1101** [LatvianModder/FTBGuides#13]
Forge v*.4.2705
FTBG v1.0.2.10

Crash Log @ https://gist.github.com/Morpheus1101/c2e5cbf03ab1691d2c85479ca0eefbee

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/770

**Comment by LatvianModder** [comment]
Also https://github.com/shadowfacts/Forgelin/issues/38
