### ISSUE TITLE
FTB GUIDE shuts at loading api [not an issue more like a problem] 1.12.2

### ISSUE THREAD

**Issue by F34RxPredator** [LatvianModder/FTBGuides#15]
Hello there im going to send in my json files as a zip file with this because it seem the FTB Guide will not open and display anything, just says its loading the api then stops working. No crashes or anything just wont work. Hence im uploading my jsons in a zip file for you to see if I have typed anything out wrong coded the json wrong etc. Im fairly new to the FTB Guides mod so I may have done something wrong. Even though my json validator claims all the jsons are fine.
[modpack_guide.zip](https://github.com/LatvianModder/FTBGuides/files/2250205/modpack_guide.zip)

**Comment by LatvianModder** [comment]
Wouldnt it make more sense to make your json like this?

```json
{
  "title": "ExPetrum - The Pack, The Guide, The Minecraft Overhaul",
  "authors": [
    "F34RxPredator"
  ],
  "icon": "item:minecraft:diamond",
  "pages": [
    {
      "id": "stoneage",
      "title": "Stone Age",
      "icon": "item:minecraft:stone"
    },
    {
      "id": "chalcolithicage",
      "title": "Chalcolithic Age",
      "icon": "item:minecraft:emerald"
    }
  ]
}
```
