### ISSUE TITLE
Server Sided Guides

### ISSUE THREAD

**Issue by Dalethium** [LatvianModder/FTBGuides#6]
First of all, I love all the work you do on these mods, it's great. 

I see there is some code related to sending guide files, but I can't quite figure out how it's supposed to work. I'd like to be able to write a guide for a server, and have all clients load the guide only when on the server -- making it a lot easier to update the guide.

**Comment by LatvianModder** [comment]
It doesn't work yet, it's just some partial code in so I can add it properly later

**Comment by LatvianModder** [comment]
See https://github.com/LatvianModder/FTBGuides/issues/4

**Comment by Dalethium** [comment]
ah ok thanks! Sorry for the double issue, the desc was empty.
