### ISSUE TITLE
Invisible guide book book

### ISSUE THREAD

**Issue by Pomidor64** [LatvianModder/FTBGuides#9]
Im playing the "FTB Pyramid Reborn" Modpack, and when i try to open the Guide Book, i don't see the pages, it's just invisible. and i can move my mouse around the screen and also close the book, but i can't see the book (i can see it in my inventory, just the when it's open). i watched youtubers play the modpack and the book worked for them perfectly fine. does anyone know what is wrong or know how to fix it?

Thank you.

**Comment by LatvianModder** [comment]
Mod is updated already, report this to pack authors
